tasks:
  - name: nextjs
    before: |
      export NUXT_TELEMETRY_DISABLED=1
      cd ui 
      npm install
      npm run build
      cd ../api
      npm install
      npm run build
    command: |
      gp open ../README.md
ports:
  - port: 3001
    onOpen: open-browser
    visibility: public
